const createActions = require('./create-actions.js').createActions

const ActionTypeSliderList = {
  INIT_MIDI_ACCESS: 'INIT_MIDI_ACCESS',
  SELECT_SLIDER_MIDI_DRIVER: 'SELECT_SLIDER_MIDI_DRIVER',
  ADD_SLIDER: 'ADD_SLIDER',
  ADD_BUTTON: 'ADD_BUTTON',
  CHANGE_BUTTON_TYPE: 'CHANGE_BUTTON_TYPE',
  DELETE: 'DELETE',
  DELETE_ALL: 'DELETE_ALL',
  TOGGLE_NOTE: 'TOGGLE_NOTE',
  CHANGE_LABEL: 'CHANGE_LABEL',
  SELECT_CC: 'SELECT_CC',
  SELECT_MIDI_CHANNEL: 'SELECT_MIDI_CHANNEL',
  HANDLE_SLIDER_CHANGE: 'HANDLE_SLIDER_CHANGE',
  SAVE_FILE: 'SAVE_FILE',
  LOAD_FILE: 'LOAD_FILE',
  CHANGE_LIST_ORDER: 'CHANGE_LIST_ORDER'
}

module.exports = {
  ...createActions(ActionTypeSliderList),
  ActionTypeSliderList
}
