version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: electronuserland/builder:wine
    - image: mono
jobs:
  deploy:
    <<: *defaults  
    steps:
      - checkout
      
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn --pure-lockfile
      - run: yarn bootstrap
      - run:
          name: Run linter and tests 
          command: yarn lint && yarn test:midi-bricks

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: ~/repo
          paths: .

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish packages
          command: yarn publish-retry
      - run:
          name: Deploy Release to github
          command: yarn deploy:midi-bricks-electron-ci
      - run:
          name: Fullfil release
          command: yarn release-ci


workflows:
  test-deploy:
    jobs:
      - deploy:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

