version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.8-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn bootstrap
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn add -W --dev electron-chromedriver
      - run: yarn test